'use client';
import { motion, PanInfo } from 'framer-motion';
import { Phone, MapPin, Edit, FileText, Share2, Loader2, Home, HeartHandshake, Users, X, Clock } from 'lucide-react';
import Link from 'next/link';
import { useAuth } from '@/lib/AuthContext';
import { useEffect, useState } from 'react';
import { jsPDF } from 'jspdf';
import { logActivity } from '@/lib/logger';
import { getBase64ImageFromUrl } from '@/lib/imageUtils';

export interface Individual {
  name: string;
  mobile?: string;
  personalMobile?: string;
  phone?: string;
  relationship?: string;
  bloodGroup?: string;
  tags?: string[];
}

export interface MemberProps {
  id?: string;
  familyName?: string;
  members?: Individual[];
  
  // UPDATED: All separated address and map fields
  currentAddress?: string;
  currentMapAddress?: string;
  currentLat?: number | null;
  currentLng?: number | null;
  currentCoordinates?: { lat: number, lng: number } | null; // Fallback for old records
  
  nativeAddress?: string;
  nativeMapAddress?: string;
  nativeLat?: number | null;
  nativeLng?: number | null;
  nativeCoordinates?: { lat: number, lng: number } | null; // Fallback for old records
  
  homeAssembly?: string;
  commendedAssembly?: string;
  primaryMobile?: string;
  photoUrl?: string;
  photoBase64?: string;
  status?: string;
  notes?: string;
  lastEdited?: string;
  hasPendingEdit?: boolean;
  onSwipeLeft?: () => void;
  onSwipeRight?: () => void;
}

export default function DirectoryCard({
  id = '', familyName = 'Unknown', members = [], 
  currentAddress = '', currentMapAddress = '', currentLat = null, currentLng = null, currentCoordinates = null, 
  nativeAddress = '', nativeMapAddress = '', nativeLat = null, nativeLng = null, nativeCoordinates = null,
  homeAssembly = '', commendedAssembly = '', primaryMobile = '', photoUrl = '', photoBase64 = '',
  status = 'Active', notes = '', lastEdited = new Date().toISOString(), hasPendingEdit = false,
  onSwipeLeft, onSwipeRight
}: MemberProps) {

  const { user, role, userProfile } = useAuth();
  const [isSharing, setIsSharing] = useState(false);
  const [isLightboxOpen, setIsLightboxOpen] = useState(false);
  const [isPhotoLoading, setIsPhotoLoading] = useState(Boolean(photoUrl || photoBase64));
  const [photoError, setPhotoError] = useState(false);

  const displayPhoto = photoUrl || photoBase64;

  useEffect(() => {
    if (!displayPhoto) {
      setIsPhotoLoading(false);
      setPhotoError(false);
      return;
    }

    setIsPhotoLoading(true);
    setPhotoError(false);
  }, [displayPhoto]);

  const formattedDate = lastEdited
    ? new Date(lastEdited).toLocaleString('en-IN', {
      timeZone: 'Asia/Kolkata',
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      hour12: true
    })
    : 'Unknown';

  const isAdmin = userProfile?.role === 'admin';

  // MERGE ADDRESS LOGIC (Safely combine manual text + map text)
  const fullCurrentAddress = [currentAddress, currentMapAddress].filter(Boolean).join(', ');
  const fullNativeAddress = [nativeAddress, nativeMapAddress].filter(Boolean).join(', ');

  // GPS FALLBACK LOGIC (Handles new schema and old schema)
  const cLat = currentLat || currentCoordinates?.lat;
  const cLng = currentLng || currentCoordinates?.lng;
  const nLat = nativeLat || nativeCoordinates?.lat;
  const nLng = nativeLng || nativeCoordinates?.lng;

  const handleSharePDF = async () => {
    setIsSharing(true);
    await logActivity(userProfile, "Exported/Shared Card", `Exported the directory card for the ${familyName}.`);
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = 210;
      const pageHeight = 297;
      const margin = 20;
      const contentWidth = pageWidth - (margin * 2);
      let yPos = 30;

      const formattedDate = new Date().toLocaleString('en-IN', {
        timeZone: 'Asia/Kolkata',
        day: '2-digit',
        month: 'short',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
        hour12: true
      });

      const addPageFooter = () => {
        pdf.setFontSize(8);
        pdf.setTextColor(150, 150, 150);
        const generatorName = user?.displayName || user?.email || 'Authorized Member';
        pdf.text(`Generated by: ${generatorName} | ${formattedDate}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
        pdf.setTextColor(0, 0, 0);
      };

      pdf.setFontSize(24);
      pdf.text('ICBA Directory', margin, yPos);
      yPos += 15;

      pdf.setFontSize(20);
      pdf.text(`${familyName}`, margin, yPos);
      yPos += 10;

      let imgDataToPrint: { dataUrl: string; width: number; height: number } | null = null;

      if (photoUrl) {
        imgDataToPrint = await getBase64ImageFromUrl(photoUrl);
      }

      if (!imgDataToPrint && photoBase64) {
        imgDataToPrint = await new Promise<{ dataUrl: string; width: number; height: number } | null>((resolve) => {
          const img = new window.Image();
          img.onload = () => resolve({ dataUrl: photoBase64, width: img.width, height: img.height });
          img.onerror = () => resolve(null);
          img.src = photoBase64;
        });
      }

      if (imgDataToPrint) {
        let printWidth = 80;
        let printHeight = 60;
        const imgRatio = imgDataToPrint.width / imgDataToPrint.height;
        const targetRatio = printWidth / printHeight;

        if (imgRatio > targetRatio) {
          printHeight = printWidth / imgRatio;
        } else {
          printWidth = printHeight * imgRatio;
        }

        if (yPos + printHeight > pageHeight - 20) {
          addPageFooter();
          pdf.addPage();
          yPos = 30;
        }

        pdf.addImage(imgDataToPrint.dataUrl, 'JPEG', margin, yPos, printWidth, printHeight);
        yPos += printHeight + 12;
      }

      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Family Members:', margin, yPos);
      pdf.setFont('helvetica', 'normal');
      yPos += 7;

      if (members.length > 0) {
        members.forEach((member: Individual) => {
          const memberText = `• ${member.name} ${member.mobile ? `(${member.mobile})` : ''}`;
          if (yPos > pageHeight - 20) { addPageFooter(); pdf.addPage(); yPos = 30; }
          pdf.text(memberText, margin + 5, yPos);
          yPos += 6;
        });
      } else {
        pdf.text('No members listed.', margin + 5, yPos);
        yPos += 6;
      }
      yPos += 5;

      const addSection = (title: string, content: string, isIndented = false) => {
        if (!content) return;
        if (yPos > pageHeight - 30) { addPageFooter(); pdf.addPage(); yPos = 30; }

        pdf.setFont('helvetica', 'bold');
        pdf.text(title, margin, yPos);
        pdf.setFont('helvetica', 'normal');

        if (isIndented) {
          yPos += 7;
          const lines = pdf.splitTextToSize(content, contentWidth - 5);
          lines.forEach((line: string) => {
            if (yPos > pageHeight - 20) { addPageFooter(); pdf.addPage(); yPos = 30; }
            pdf.text(line, margin + 5, yPos);
            yPos += 6;
          });
          yPos += 2;
        } else {
          pdf.text(content, margin + 40, yPos);
          yPos += 10;
        }
      };

      addSection('Primary Mobile:', primaryMobile || '');
      // UPDATED to use full combined addresses in the PDF
      addSection('Current Address:', fullCurrentAddress, true);
      addSection('Native Address:', fullNativeAddress, true);
      addSection('Home Assembly:', homeAssembly || '');
      addSection('Commended Assembly:', commendedAssembly || '');
      addSection('Additional Info:', notes || '', true);

      addPageFooter();

      const pdfBlob = pdf.output('blob');
      const file = new File([pdfBlob], `${familyName}_Family_Directory.pdf`, { type: 'application/pdf' });
      if (navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({ files: [file], title: `${familyName} Details` });
      } else {
        pdf.save(`${familyName}_Family_Directory.pdf`);
      }
    } catch (error) {
      console.error('Error generating/sharing PDF:', error);
      alert('Could not share PDF. Your device may not support file sharing.');
    } finally {
      setIsSharing(false);
    }
  };

  return (
    <>
      {isLightboxOpen && displayPhoto && (
        <div className="fixed inset-0 z-[100] bg-black/95 flex items-center justify-center p-4" onClick={() => setIsLightboxOpen(false)}>
          <button className="absolute top-6 right-6 text-white p-2 bg-white/10 rounded-full hover:bg-white/20 transition"><X size={24} /></button>
          <img
            src={displayPhoto}
            onError={(e) => {
              if (photoBase64 && e.currentTarget.src !== photoBase64) {
                e.currentTarget.src = photoBase64;
              }
            }}
            alt="Full size"
            className="max-w-full max-h-[90vh] object-contain"
            onClick={(e) => e.stopPropagation()}
          />
        </div>
      )}

      <motion.div
        className="w-full bg-white flex flex-col relative shadow-sm rounded-b-2xl print:shadow-none"
        drag="x"
        dragConstraints={{ left: 0, right: 0 }}
        onDragEnd={(event: MouseEvent | TouchEvent | PointerEvent, info: PanInfo) => {
          const swipe = Math.abs(info.offset.x) * info.velocity.x;
          if (swipe < -10000 && onSwipeLeft) onSwipeLeft();
          else if (swipe > 10000 && onSwipeRight) onSwipeRight();
        }}
      >
        <div className="p-6 border-b border-slate-100 flex justify-between items-start gap-4">
          <div className="flex-1 min-w-0">
            <h2
              className="text-2xl font-serif font-bold text-slate-900 truncate w-full block"
              title={familyName}
            >
              {familyName}
            </h2>
            {status === 'Inactive' && (
              <div className="mt-2 flex items-center gap-2">
                <span className="inline-flex items-center gap-2 rounded-full border border-rose-200 bg-rose-50 px-3 py-1 text-[11px] font-bold uppercase tracking-[0.25em] text-rose-700 shadow-sm">
                  <span className="h-2 w-2 rounded-full bg-rose-500" />
                  Inactive
                </span>
              </div>
            )}
          </div>

          <div className="flex space-x-2 print:hidden shrink-0 mt-1">
            <button onClick={handleSharePDF} disabled={isSharing} className="p-2.5 bg-slate-100 text-slate-700 rounded-lg hover:bg-slate-200 transition flex items-center">
              {isSharing ? <Loader2 size={18} className="animate-spin" /> : <Share2 size={18} />}
            </button>

            {user && id && (
              isAdmin || !hasPendingEdit ? (
                <Link href={`/edit-family/${id}`} className="px-4 py-2 bg-slate-100 text-slate-700 rounded-lg text-sm font-medium hover:bg-slate-200 flex items-center transition">
                  <Edit size={16} className="mr-2" /> Edit
                </Link>
              ) : (
                <div className="px-4 py-2 bg-amber-50 text-amber-700 rounded-lg text-sm font-medium border border-amber-200 flex items-center cursor-not-allowed opacity-80" title="An edit is waiting for admin approval">
                  <Clock size={16} className="mr-1.5" /> Pending
                </div>
              )
            )}
          </div>
        </div>

        {displayPhoto ? (
          <div className="relative w-full aspect-[4/3] bg-slate-50 print:hidden overflow-hidden cursor-pointer group" onClick={() => setIsLightboxOpen(true)}>
            {isPhotoLoading && !photoError && (
              <div className="absolute inset-0 z-10 flex items-center justify-center bg-slate-100/90 backdrop-blur-sm">
                <div className="flex h-14 w-14 items-center justify-center rounded-full border border-slate-200 bg-white/90 shadow-sm">
                  <Loader2 size={24} className="animate-spin text-teal-600" />
                </div>
              </div>
            )}
            {!photoError ? (
              <img
                src={displayPhoto}
                onLoad={() => setIsPhotoLoading(false)}
                onError={(e) => {
                  setIsPhotoLoading(false);
                  setPhotoError(true);
                  if (photoBase64 && e.currentTarget.src !== photoBase64) {
                    e.currentTarget.src = photoBase64;
                  } else {
                    e.currentTarget.style.display = 'none';
                  }
                }}
                alt={`${familyName}`}
                className={`h-full w-full object-cover object-center transition duration-300 group-hover:scale-105 ${isPhotoLoading ? 'opacity-0' : 'opacity-100'}`}
              />
            ) : (
              <div className="flex h-full w-full items-center justify-center bg-gradient-to-r from-teal-600 to-teal-800">
                <Users size={32} className="text-white opacity-40" />
              </div>
            )}
            <div className="absolute inset-0 bg-black/0 group-hover:bg-black/10 transition flex items-center justify-center">
              <span className="bg-black/60 text-white px-4 py-2 rounded-full opacity-0 group-hover:opacity-100 transition text-sm font-medium backdrop-blur-sm">Click to expand</span>
            </div>
          </div>
        ) : (
          <div className="h-24 w-full bg-gradient-to-r from-teal-600 to-teal-800 flex items-center justify-center print:hidden">
            <Users size={32} className="text-white opacity-40" />
          </div>
        )}

        <div className="p-6 space-y-8">
          {members.length > 0 && (
            <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
              <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">Member Contacts</h3>
              <div className="space-y-3">
                {members.map((member, index) => {
                  const memberPhone = member.personalMobile || member.mobile || member.phone;
                  return (
                    <div key={`${member.name}-${index}`} className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm">
                      <div className="flex items-start justify-between gap-3">
                        <div className="min-w-0">
                          <p className="font-semibold text-slate-900">{member.name}</p>
                          {member.relationship && (
                            <p className="mt-1 text-[11px] font-semibold uppercase tracking-[0.2em] text-slate-400">{member.relationship}</p>
                          )}
                        </div>
                        {memberPhone ? (
                          <a href={`tel:${memberPhone}`} className="inline-flex shrink-0 items-center gap-2 rounded-full bg-teal-50 px-3 py-1.5 text-sm font-semibold text-teal-700 transition hover:bg-teal-100">
                            <Phone size={14} /> {memberPhone}
                          </a>
                        ) : (
                          <span className="text-sm text-slate-400">No phone</span>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {members.length > 0 && (
            <div>
              <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-2">Family Members</h3>
              <p className="text-slate-800 font-medium leading-relaxed">
                {members.map(m => m.name).join(', ')}
              </p>
            </div>
          )}

          <div>
            <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-4">Contact Info</h3>
            <div className="space-y-4 text-slate-700">
              {primaryMobile && (
                <div className="flex items-center gap-3">
                  <Phone size={20} className="text-teal-600 shrink-0" />
                  <a href={`tel:${primaryMobile}`} className="font-medium hover:text-teal-700">{primaryMobile}</a>
                </div>
              )}
              
              {/* FIXED LINK AND COMBINED TEXT */}
              {fullCurrentAddress && (
                <a
                  href={cLat && cLng 
                    ? `https://maps.google.com/?q=${cLat},${cLng}` 
                    : `https://maps.google.com/?q=${encodeURIComponent(fullCurrentAddress)}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-start gap-3 group block"
                >
                  <MapPin size={20} className="text-teal-600 mt-1 shrink-0 group-hover:text-teal-800 transition" />
                  <div>
                    <p className="leading-snug text-sm font-bold text-slate-800 mb-0.5 group-hover:text-teal-700 transition">Current Address</p>
                    <p className="leading-snug group-hover:text-teal-600 transition">{fullCurrentAddress}</p>
                  </div>
                </a>
              )}

              {/* FIXED LINK AND COMBINED TEXT */}
              {fullNativeAddress && (
                <a
                  href={nLat && nLng 
                    ? `https://maps.google.com/?q=${nLat},${nLng}` 
                    : `https://maps.google.com/?q=${encodeURIComponent(fullNativeAddress)}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-start gap-3 group block"
                >
                  <MapPin size={20} className="text-slate-400 mt-1 shrink-0 group-hover:text-teal-600 transition" />
                  <div>
                    <p className="leading-snug text-sm font-bold text-slate-800 mb-0.5 group-hover:text-teal-700 transition">Native Address</p>
                    <p className="leading-snug text-slate-600 group-hover:text-teal-600 transition">{fullNativeAddress}</p>
                  </div>
                </a>
              )}
            </div>
          </div>

          {(homeAssembly || commendedAssembly || notes) && (
            <div>
              <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-3">Additional Info</h3>
              <div className="space-y-3 bg-slate-50 p-4 rounded-xl border border-slate-100">
                {homeAssembly && (
                  <div className="flex items-start gap-3 text-slate-700">
                    <Home size={18} className="text-teal-600 shrink-0 mt-0.5" />
                    <div>
                      <p className="text-xs font-bold text-slate-500 uppercase">Home Assembly</p>
                      <p className="text-sm font-medium">{homeAssembly}</p>
                    </div>
                  </div>
                )}
                {commendedAssembly && (
                  <div className="flex items-start gap-3 text-slate-700">
                    <HeartHandshake size={18} className="text-teal-600 shrink-0 mt-0.5" />
                    <div>
                      <p className="text-xs font-bold text-slate-500 uppercase">Commended Assembly</p>
                      <p className="text-sm font-medium">{commendedAssembly}</p>
                    </div>
                  </div>
                )}
                {notes && (
                  <div className="flex items-start gap-3 text-slate-700 pt-2 border-t border-slate-200 mt-2">
                    <FileText size={18} className="text-teal-600 shrink-0 mt-0.5" />
                    <p className="text-sm leading-relaxed">{notes}</p>
                  </div>
                )}
              </div>
            </div>
          )}
          <div className="pt-4 border-t border-slate-100 text-xs text-slate-400">Last Modified: {formattedDate}</div>
        </div>
      </motion.div>
    </>
  );
}